apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-awesome
  description: Team Awesome
  namespace: mae
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-awesome@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Mae
  title: Mae Large
  description: PVE
  namespace: mae
spec:
  profile:
    displayName: Mae Large
    email: mae.large@broadcom.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-awesome]
